### PR TITLE
nmparser: don't omit zero for times in run_details JSON output

### PR DESCRIPTION
**Pull request by kyleam**
As @barrettk noted in gh-273, `bbi nonmem summary` doesn't report `postprocess_time` if it has a value of zero.  (There are a few cases of this in both bbi's and bbr's test suite.)  The same applies to `cpu_time`.

This PR fixes that by dropping the `omitempty` tag from the `RunDetails` struct.

### CODE REVIEW

**Review by barrettk — APPROVED** [review]
Looks good to me. Can you cc me when you release this new dev version? Would like to use it for testing in one of my PR's

**Comment by kyleam** [comment]
> Can you cc me when you release this new dev version?

Even once this is merged, things are held up by alpha2 being at the tip of the unmerged gh-268.  It'd be confusing to have an alpha3 that doesn't have alpha2 as an ancestor, so I'd like to avoid making any alpha3 tag until that is brought in.  (And in general would prefer to batch these alpha releases a bit more, though when we decided to bring alpha1 into the main line makes things trickier given how `skip_if_old_bbi` handles dev versions).

Anyway, a lot of this depends on the specifics, but for now I can at least help you get set up locally to build this bbi and point bbr to it, if you'd like.

**Comment by seth127** [comment]
I just approved #268 (and looking at #272) now. Feel free to merge and tag however y'all think is best.

**Comment by kyleam** [comment]
With merge of gh-268, there was direct conflict in `validation/requirements.yaml` and semantic conflicts in `validation/stories.yaml` and `acop-nan.golden.json`.  Rebased.

<details>
<summary>range-diff</summary>

```
$ git range-diff main origin/run-details-keep-0-time run-details-keep-0-time
1:  224b6b0 = 1:  d0241d6 integration: change CPU time for 12/ to test zero case
2:  5b8daba ! 2:  52db86e nmparser: don't omit zero for times in run_details JSON output
    @@ integration/testdata/bbi_summary/aa_golden_files/acop-iov.golden.json
      		"function_evaluations": 457,
      		"significant_digits": 3.1,
     
    + ## integration/testdata/bbi_summary/aa_golden_files/acop-nan.golden.json ##
    +@@
    + 		"covariance_time": [
    + 			0.56
    + 		],
    ++		"postprocess_time": 0,
    + 		"cpu_time": 2.543,
    + 		"function_evaluations": 366,
    + 		"significant_digits": 3.2,
    +
      ## integration/testdata/bbi_summary/aa_golden_files/acop.golden.json ##
     @@
      		"covariance_time": [
    @@ parsers/nmparser/structs.go: type RunDetails struct {
      	ProblemText         string    `json:"problem_text,omitempty"`
     
      ## validation/requirements.yaml ##
    -@@ validation/requirements.yaml: SUM-R005:
    +@@ validation/requirements.yaml: SUM-R006:
        tests:
    +   - UNIT-NMP-019
        - INT-SUM-001
    -   - UNIT-NMP-035
    -+SUM-R006:
    ++SUM-R007:
     +  description: BBI summary includes times that are zero
     +  tests:
     +  - INT-SUM-001
    @@ validation/requirements.yaml: SUM-R005:
     
      ## validation/stories.yaml ##
     @@ validation/stories.yaml: BBI-SUM-001:
    -   - SUM-R003
        - SUM-R004
        - SUM-R005
    -+  - SUM-R006
    +   - SUM-R006
    ++  - SUM-R007
      BBI-COV-001:
        name: Parse .cov and .cor files
        description: As a user, I want to be able to parse the `.cov` and `.cor` files in
```

</details>

**Comment by kyleam** [comment]
Hmm, there are [CI failures](https://github-drone.metrumrg.com/metrumresearchgroup/bbi/868), but I don't think they're specific to this PR.  The [build](https://github-drone.metrumrg.com/metrumresearchgroup/bbi/866/2/6) triggered with the merge of gh-268 looks to have the same failures.  Hmm, and confusingly I don't think it's a matter of a bad interaction with the new base from the merge, because the base (f090539) hasn't changed since 268 had [a successful run](https://github-drone.metrumrg.com/metrumresearchgroup/bbi/857).

<details>
<summary>failures</summary>

```
grep '^{' bbi-fail-274.log | jq 'select(.Output != null and (.Output | contains("--- FAIL")))'
```

```json
{
  "Time": "2022-07-15T11:43:34.307249525-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithoutPrefix",
  "Output": "--- FAIL: TestBBIExpandsWithoutPrefix (27.01s)\n"
}
{
  "Time": "2022-07-15T11:43:34.307255441-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithoutPrefix/[INT-EXP-001]",
  "Output": "    --- FAIL: TestBBIExpandsWithoutPrefix/[INT-EXP-001] (27.01s)\n"
}
{
  "Time": "2022-07-15T11:43:34.307261767-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/101.ctl[INT-EXP-001]",
  "Output": "        --- FAIL: TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/101.ctl[INT-EXP-001] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:34.30727416-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/102.ctl[INT-EXP-001]",
  "Output": "        --- FAIL: TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/102.ctl[INT-EXP-001] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:34.307284428-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/103.ctl[INT-EXP-001]",
  "Output": "        --- FAIL: TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/103.ctl[INT-EXP-001] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:34.307295809-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/104.ctl[INT-EXP-001]",
  "Output": "        --- FAIL: TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/104.ctl[INT-EXP-001] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:34.307309125-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/105.ctl[INT-EXP-001]",
  "Output": "        --- FAIL: TestBBIExpandsWithoutPrefix/[INT-EXP-001]//data/868/working/bbi_expansion/model/105.ctl[INT-EXP-001] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:50.090415294-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefix",
  "Output": "--- FAIL: TestBBIExpandsWithPrefix (15.78s)\n"
}
{
  "Time": "2022-07-15T11:43:50.090424959-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefix/[INT-EXP-002]",
  "Output": "    --- FAIL: TestBBIExpandsWithPrefix/[INT-EXP-002] (15.78s)\n"
}
{
  "Time": "2022-07-15T11:43:50.090431151-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefix/[INT-EXP-002]//data/868/working/bbi_expansion/model/bbi_mainrun_101.ctl[INT-EXP-002]",
  "Output": "        --- FAIL: TestBBIExpandsWithPrefix/[INT-EXP-002]//data/868/working/bbi_expansion/model/bbi_mainrun_101.ctl[INT-EXP-002] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:50.090443358-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefix/[INT-EXP-002]//data/868/working/bbi_expansion/model/bbi_mainrun_102.ctl[INT-EXP-002]",
  "Output": "        --- FAIL: TestBBIExpandsWithPrefix/[INT-EXP-002]//data/868/working/bbi_expansion/model/bbi_mainrun_102.ctl[INT-EXP-002] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:50.090453474-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefix/[INT-EXP-002]//data/868/working/bbi_expansion/model/bbi_mainrun_103.ctl[INT-EXP-002]",
  "Output": "        --- FAIL: TestBBIExpandsWithPrefix/[INT-EXP-002]//data/868/working/bbi_expansion/model/bbi_mainrun_103.ctl[INT-EXP-002] (0.00s)\n"
}
{
  "Time": "2022-07-15T11:43:57.888888675-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefixToPartialMatch",
  "Output": "--- FAIL: TestBBIExpandsWithPrefixToPartialMatch (7.80s)\n"
}
{
  "Time": "2022-07-15T11:43:57.888894459-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefixToPartialMatch/bbi_expansion[INT-EXP-003]",
  "Output": "    --- FAIL: TestBBIExpandsWithPrefixToPartialMatch/bbi_expansion[INT-EXP-003] (7.80s)\n"
}
{
  "Time": "2022-07-15T11:43:57.888900331-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIExpandsWithPrefixToPartialMatch/bbi_expansion[INT-EXP-003]//data/868/working/bbi_expansion/model/bbi_mainrun_102.ctl",
  "Output": "        --- FAIL: TestBBIExpandsWithPrefixToPartialMatch/bbi_expansion[INT-EXP-003]//data/868/working/bbi_expansion/model/bbi_mainrun_102.ctl (0.00s)\n"
}
{
  "Time": "2022-07-15T11:44:03.407981904-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesLocalExecution",
  "Output": "--- FAIL: TestBbiCompletesLocalExecution (5.52s)\n"
}
{
  "Time": "2022-07-15T11:44:03.408025673-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesLocalExecution/acop[INT-LOCAL-001]",
  "Output": "    --- FAIL: TestBbiCompletesLocalExecution/acop[INT-LOCAL-001] (5.50s)\n"
}
{
  "Time": "2022-07-15T11:44:03.40803236-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesLocalExecution/acop[INT-LOCAL-001]/acop",
  "Output": "        --- FAIL: TestBbiCompletesLocalExecution/acop[INT-LOCAL-001]/acop (5.49s)\n"
}
{
  "Time": "2022-07-15T11:44:33.559887697-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMFEOptionsEndInScript",
  "Output": "--- FAIL: TestNMFEOptionsEndInScript (30.15s)\n"
}
{
  "Time": "2022-07-15T11:44:33.559921199-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMFEOptionsEndInScript/240[INT-LOCAL-002]",
  "Output": "    --- FAIL: TestNMFEOptionsEndInScript/240[INT-LOCAL-002] (9.73s)\n"
}
{
  "Time": "2022-07-15T11:44:33.559929066-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMFEOptionsEndInScript/240[INT-LOCAL-002]/Executable_MTP",
  "Output": "        --- FAIL: TestNMFEOptionsEndInScript/240[INT-LOCAL-002]/Executable_MTP (9.71s)\n"
}
{
  "Time": "2022-07-15T11:44:33.559948074-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMFEOptionsEndInScript/acop[INT-LOCAL-002]",
  "Output": "    --- FAIL: TestNMFEOptionsEndInScript/acop[INT-LOCAL-002] (10.37s)\n"
}
{
  "Time": "2022-07-15T11:44:33.559953667-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMFEOptionsEndInScript/acop[INT-LOCAL-002]/acop",
  "Output": "        --- FAIL: TestNMFEOptionsEndInScript/acop[INT-LOCAL-002]/acop (10.35s)\n"
}
{
  "Time": "2022-07-15T11:44:33.559974378-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMFEOptionsEndInScript/ctl_test[INT-LOCAL-002]",
  "Output": "    --- FAIL: TestNMFEOptionsEndInScript/ctl_test[INT-LOCAL-002] (10.01s)\n"
}
{
  "Time": "2022-07-15T11:44:33.559979599-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMFEOptionsEndInScript/ctl_test[INT-LOCAL-002]/Executable_MTP",
  "Output": "        --- FAIL: TestNMFEOptionsEndInScript/ctl_test[INT-LOCAL-002]/Executable_MTP (9.99s)\n"
}
{
  "Time": "2022-07-15T11:44:49.726199672-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiParallelExecution",
  "Output": "--- FAIL: TestBbiParallelExecution (16.17s)\n"
}
{
  "Time": "2022-07-15T11:44:49.726230214-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiParallelExecution/240[INT-LOCAL-003]",
  "Output": "    --- FAIL: TestBbiParallelExecution/240[INT-LOCAL-003] (5.32s)\n"
}
{
  "Time": "2022-07-15T11:44:49.726241311-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiParallelExecution/240[INT-LOCAL-003]/Executable_MTP",
  "Output": "        --- FAIL: TestBbiParallelExecution/240[INT-LOCAL-003]/Executable_MTP (5.30s)\n"
}
{
  "Time": "2022-07-15T11:44:49.726261767-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiParallelExecution/acop[INT-LOCAL-003]",
  "Output": "    --- FAIL: TestBbiParallelExecution/acop[INT-LOCAL-003] (5.36s)\n"
}
{
  "Time": "2022-07-15T11:44:49.726267407-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiParallelExecution/acop[INT-LOCAL-003]/acop",
  "Output": "        --- FAIL: TestBbiParallelExecution/acop[INT-LOCAL-003]/acop (5.34s)\n"
}
{
  "Time": "2022-07-15T11:44:49.726281225-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiParallelExecution/ctl_test[INT-LOCAL-003]",
  "Output": "    --- FAIL: TestBbiParallelExecution/ctl_test[INT-LOCAL-003] (5.41s)\n"
}
{
  "Time": "2022-07-15T11:44:49.726287325-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiParallelExecution/ctl_test[INT-LOCAL-003]/Executable_MTP",
  "Output": "        --- FAIL: TestBbiParallelExecution/ctl_test[INT-LOCAL-003]/Executable_MTP (5.34s)\n"
}
{
  "Time": "2022-07-15T11:45:54.544328732-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesSGEExecution",
  "Output": "--- FAIL: TestBbiCompletesSGEExecution (60.09s)\n"
}
{
  "Time": "2022-07-15T11:45:54.544335372-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesSGEExecution/acop[INT-SGE-001]",
  "Output": "    --- FAIL: TestBbiCompletesSGEExecution/acop[INT-SGE-001] (30.05s)\n"
}
{
  "Time": "2022-07-15T11:45:54.544341079-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesSGEExecution/acop[INT-SGE-001]/acop",
  "Output": "        --- FAIL: TestBbiCompletesSGEExecution/acop[INT-SGE-001]/acop (30.03s)\n"
}
{
  "Time": "2022-07-15T11:45:54.544362136-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesSGEExecution/ctl_test[INT-SGE-001]",
  "Output": "    --- FAIL: TestBbiCompletesSGEExecution/ctl_test[INT-SGE-001] (30.05s)\n"
}
{
  "Time": "2022-07-15T11:45:54.544369407-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesSGEExecution/ctl_test[INT-SGE-001]/Executable_MTP",
  "Output": "        --- FAIL: TestBbiCompletesSGEExecution/ctl_test[INT-SGE-001]/Executable_MTP (30.03s)\n"
}
{
  "Time": "2022-07-15T11:47:24.681580247-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesParallelSGEExecution",
  "Output": "--- FAIL: TestBbiCompletesParallelSGEExecution (90.14s)\n"
}
{
  "Time": "2022-07-15T11:47:24.681584449-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesParallelSGEExecution/240[INT-SGE-002]",
  "Output": "    --- FAIL: TestBbiCompletesParallelSGEExecution/240[INT-SGE-002] (30.05s)\n"
}
{
  "Time": "2022-07-15T11:47:24.681588841-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesParallelSGEExecution/240[INT-SGE-002]/Executable_MTP",
  "Output": "        --- FAIL: TestBbiCompletesParallelSGEExecution/240[INT-SGE-002]/Executable_MTP (30.03s)\n"
}
{
  "Time": "2022-07-15T11:47:24.681601874-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesParallelSGEExecution/acop[INT-SGE-002]",
  "Output": "    --- FAIL: TestBbiCompletesParallelSGEExecution/acop[INT-SGE-002] (30.05s)\n"
}
{
  "Time": "2022-07-15T11:47:24.681605625-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesParallelSGEExecution/acop[INT-SGE-002]/acop",
  "Output": "        --- FAIL: TestBbiCompletesParallelSGEExecution/acop[INT-SGE-002]/acop (30.03s)\n"
}
{
  "Time": "2022-07-15T11:47:24.681623963-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesParallelSGEExecution/ctl_test[INT-SGE-002]",
  "Output": "    --- FAIL: TestBbiCompletesParallelSGEExecution/ctl_test[INT-SGE-002] (30.05s)\n"
}
{
  "Time": "2022-07-15T11:47:24.681631635-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBbiCompletesParallelSGEExecution/ctl_test[INT-SGE-002]/Executable_MTP",
  "Output": "        --- FAIL: TestBbiCompletesParallelSGEExecution/ctl_test[INT-SGE-002]/Executable_MTP (30.03s)\n"
}
{
  "Time": "2022-07-15T11:47:42.641016624-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIConfigJSONCreated",
  "Output": "--- FAIL: TestBBIConfigJSONCreated (16.93s)\n"
}
{
  "Time": "2022-07-15T11:47:42.641057327-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIConfigJSONCreated/240[INT-CFG-001]",
  "Output": "    --- FAIL: TestBBIConfigJSONCreated/240[INT-CFG-001] (6.07s)\n"
}
{
  "Time": "2022-07-15T11:47:42.641064734-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIConfigJSONCreated/240[INT-CFG-001]/Executable_MTP",
  "Output": "        --- FAIL: TestBBIConfigJSONCreated/240[INT-CFG-001]/Executable_MTP (6.00s)\n"
}
{
  "Time": "2022-07-15T11:47:42.641102295-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIConfigJSONCreated/acop[INT-CFG-001]",
  "Output": "    --- FAIL: TestBBIConfigJSONCreated/acop[INT-CFG-001] (5.66s)\n"
}
{
  "Time": "2022-07-15T11:47:42.641107438-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIConfigJSONCreated/acop[INT-CFG-001]/acop",
  "Output": "        --- FAIL: TestBBIConfigJSONCreated/acop[INT-CFG-001]/acop (5.64s)\n"
}
{
  "Time": "2022-07-15T11:47:42.641120419-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIConfigJSONCreated/ctl_test[INT-CFG-001]",
  "Output": "    --- FAIL: TestBBIConfigJSONCreated/ctl_test[INT-CFG-001] (5.17s)\n"
}
{
  "Time": "2022-07-15T11:47:42.641125637-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestBBIConfigJSONCreated/ctl_test[INT-CFG-001]/Executable_MTP",
  "Output": "        --- FAIL: TestBBIConfigJSONCreated/ctl_test[INT-CFG-001]/Executable_MTP (5.15s)\n"
}
{
  "Time": "2022-07-15T11:47:47.896061079-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestConfigValuesAreCorrectInWrittenFile",
  "Output": "--- FAIL: TestConfigValuesAreCorrectInWrittenFile (5.25s)\n"
}
{
  "Time": "2022-07-15T11:47:47.896068963-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestConfigValuesAreCorrectInWrittenFile/Executable_MTP[INT-CFG-002]",
  "Output": "    --- FAIL: TestConfigValuesAreCorrectInWrittenFile/Executable_MTP[INT-CFG-002] (5.22s)\n"
}
{
  "Time": "2022-07-15T11:47:52.920818395-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestHasValidDataPathForCTL",
  "Output": "--- FAIL: TestHasValidDataPathForCTL (5.02s)\n"
}
{
  "Time": "2022-07-15T11:47:52.920827219-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestHasValidDataPathForCTL/validPathCTL_Executable_MTP.ctl[INT-DATA-001]",
  "Output": "    --- FAIL: TestHasValidDataPathForCTL/validPathCTL_Executable_MTP.ctl[INT-DATA-001] (5.00s)\n"
}
{
  "Time": "2022-07-15T11:48:03.139855471-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestHasValidComplexPathCTLAndMod",
  "Output": "--- FAIL: TestHasValidComplexPathCTLAndMod (10.18s)\n"
}
{
  "Time": "2022-07-15T11:48:03.139862032-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestHasValidComplexPathCTLAndMod/validComplexPathFor_Executable_MTP.ctl[INT-DATA-003]",
  "Output": "    --- FAIL: TestHasValidComplexPathCTLAndMod/validComplexPathFor_Executable_MTP.ctl[INT-DATA-003] (5.24s)\n"
}
{
  "Time": "2022-07-15T11:48:03.139874933-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestHasValidComplexPathCTLAndMod/validComplexPathFor_Executable_MTP2.mod[INT-DATA-003]",
  "Output": "    --- FAIL: TestHasValidComplexPathCTLAndMod/validComplexPathFor_Executable_MTP2.mod[INT-DATA-003] (4.92s)\n"
}
{
  "Time": "2022-07-15T11:48:08.953031684-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMQUALExecutionSucceeds",
  "Output": "--- FAIL: TestNMQUALExecutionSucceeds (5.76s)\n"
}
{
  "Time": "2022-07-15T11:48:08.953038496-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestNMQUALExecutionSucceeds/Executable_MTP[INT-NMQ-001]",
  "Output": "    --- FAIL: TestNMQUALExecutionSucceeds/Executable_MTP[INT-NMQ-001] (5.74s)\n"
}
{
  "Time": "2022-07-15T11:48:14.242098021-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestHashingForNMQualWorksWithOriginalModFile",
  "Output": "--- FAIL: TestHashingForNMQualWorksWithOriginalModFile (5.29s)\n"
}
{
  "Time": "2022-07-15T11:48:14.242104143-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestHashingForNMQualWorksWithOriginalModFile/Executable_MTP[INT-NMQ-002]",
  "Output": "    --- FAIL: TestHashingForNMQualWorksWithOriginalModFile/Executable_MTP[INT-NMQ-002] (5.27s)\n"
}
{
  "Time": "2022-07-15T11:48:18.879436804-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestPostExecutionSucceeds",
  "Output": "--- FAIL: TestPostExecutionSucceeds (4.64s)\n"
}
{
  "Time": "2022-07-15T11:48:18.879473518-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestPostExecutionSucceeds/acop[INT-POSTEX-002]",
  "Output": "    --- FAIL: TestPostExecutionSucceeds/acop[INT-POSTEX-002] (4.61s)\n"
}
{
  "Time": "2022-07-15T11:48:18.879479263-04:00",
  "Action": "output",
  "Package": "github.com/metrumresearchgroup/bbi/integration",
  "Test": "TestPostExecutionSucceeds/acop[INT-POSTEX-002]/acop_post_execution",
  "Output": "        --- FAIL: TestPostExecutionSucceeds/acop[INT-POSTEX-002]/acop_post_execution (4.59s)\n"
}
```

</details>

**Pull request merged**
