### PR TITLE
Expand docs and set up site

### PR DESCRIPTION
**Pull request by kyleam**
This PR reworks and expands the command-line docs and sets up a static site.

As with the [sister PR in pkgr](https://github.com/metrumresearchgroup/pkgr/pull/422), there's more that can be done here, but I think this is in a good stopping place.

GitHub Actions is set up to deploy the site on release. A build can also be triggered by pushing to `scratch/deploy-site`, which I've used to publish what's currently at https://metrumresearchgroup.github.io/bbi/

---

- [x] wait on merge of base (gh-330)

### CODE REVIEW

**Comment by kyleam** [comment]
lint workflow flags two things:

```
2024-08-21T17:24:15.5824839Z ##[error]cmd/root.go:75:2: SA1019: rand.Seed has been deprecated since Go 1.20 and an alternative has been available since Go 1.0: As of Go 1.20 there is no reason to call Seed with a random value. Programs that call Seed with a known value to get a specific sequence of results should use New(NewSource(seed)) to obtain a local random generator. (staticcheck)
2024-08-21T17:24:15.5836135Z 	rand.Seed(time.Now().UnixNano())
2024-08-21T17:24:15.5836700Z 	^
2024-08-21T17:24:15.5841269Z ##[error]cmd/params.go:19:2: SA1019: "io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided by package [io] or package [os], and those implementations should be preferred in new code. See the specific function documentation for details. (staticcheck)
2024-08-21T17:24:15.5844512Z 	"io/ioutil"
2024-08-21T17:24:15.5845568Z 	^
```

Neither of those were changed in this PR.  I'll open separate PRs to fix those.

**Comment by kyleam** [comment]
Pushed update to 1) change base to gh-330 to fix lint workflow and 2) add package name to navigation bar (because unlike pkgr, bbi doesn't have a package-specific logo with the package name in it).

**Comment by seth127** [comment]
This is all looking great. I basically have the same comments as I put into [this review of the sister `pkgr` PR](https://github.com/metrumresearchgroup/pkgr/pull/422#pullrequestreview-2257778267), in terms of adding README documentation of the machinery to render/publish the site, build the docs, etc.

Thanks.

**Comment by kyleam** [comment]
Thanks @seth127

Pushed an update to 

 * add `README.md` to `docs/site/`
 * replace out-of-date development section with one that points to `docs/site/README.md` and `internal/valtools/README.md`
 * add link to website to top of root `README.md`, as discussed offline

**Review by seth127 — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
