### PR TITLE
validation: requirements cleanup

### PR DESCRIPTION
**Pull request by kyleam**
Prune unlinked requirements, and eliminate requirement ID gaps.

### CODE REVIEW

**Comment by barrettk** [comment]
Just to get some additional context, was there a reason you chose to remove all those requirements vs. adding them to new stories? Its tough to know from an outside perspective, but most look like they're related to helper functions/might not be important enough to include, but just wanted to be sure.

**Comment by kyleam** [comment]
> was there a reason you chose to remove all those requirements vs. adding them to new stories?

To expand on what I said in the commit message...

```
validation: prune unlinked requirements

The previous release didn't have requirements (stories were linked
directly to tests).  A script generated requirements.yaml based on the
tests, but that includes a lot of requirements that aren't actually
linked to a story (because the corresponding test ID wasn't either).

Clean these up.
```


... these extra ones are just artifacts of the import process.  We are retaining all the stories that are currently in the validation docs and adding one more.

So, perhaps someone will decide we need to flesh out bbi's stories, but 1) I'm not pushing for that and 2) the decision to move from `tests -> stories` to `tests -> requirements -> stories` does not imply that we need to change the current state of bbi's stories.

**Comment by barrettk** [comment]
Yeah ok that makes sense. Thanks for the additional context

**Review by barrettk — APPROVED** [review]
Looks good

**Comment by kyleam** [comment]
@barrettk Thanks for the review.  Not the most exciting thing to look through :)

**Pull request merged**
